[CUDA_Runtime_jll]
__clear__ = ["local"]
version = "12.5"

[AcademicClusters]
gadi_project = "xr78"
gadi_storage = "gdata/xr78+scratch/xr78"

[AllenNeuropixelsBase]
datadir = "/import/taiji1/bhar9988/code/DDC/AllenNeuropixelsBase.jl/data"

[SpatiotemporalMotifs]
gamma = "(30, 100)"
theta = "(3, 10)"
causal_filter = "false"
