#! /bin/bash

# ? Prior to this script, you should have EITHER:
# ?     1. Downloaded the precomputed plot data, OR:
# ?     2. Run the all the calculation scripts, as described in the README, to generate the plot data.

PROJECT_DIR="$(dirname "$(realpath "$0")")"

bash "$PROJECT_DIR/scripts/Fig1_combined_curves.jl"
bash "$PROJECT_DIR/scripts/Fig2_bFNS.jl"
bash "$PROJECT_DIR/scripts/Fig3_effective_theory.jl"
bash "$PROJECT_DIR/scripts/Fig4_hierarchical_variation.jl"
bash "$PROJECT_DIR/scripts/FigS23_summaries.jl"
bash "$PROJECT_DIR/scripts/FigS4_input_parameters.jl"
