name = "WorkingRegime"
uuid = "a2fb53ce-e249-4e8c-8865-d217552c1552"
version = "1.0.0-DEV"
authors = ["brendanjohnharris <bhar9988@uni.sydney.edu.au> and contributors"]

[workspace]
projects = ["WRCircuit, WRExperiment", "WRTheory"]

[deps]
AcademicClusters = "0d53aa51-fded-4285-958f-a79747f7b7b4"
CairoMakie = "13f3f980-e62b-5c42-98c6-ff1f3baf88f0"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
DrWatson = "634d3b9d-ee7a-5ddf-bec9-22491ea816e1"
Fathom = "05518021-a905-466c-bf96-cf0c89e1b0a0"
JLD2 = "033835bb-8acc-5ee8-8aae-3f567f8a3819"
TimeseriesTools = "380cddd1-6ef2-46ca-b087-e7151fb095ff"

[sources]
Fathom = {rev = "main", url = "https://github.com/brendanjohnharris/Fathom.jl"}
TimeseriesTools = {path="../../TimeseriesTools.jl"}

[extras]
CUDA_Runtime_jll = "76a88914-d11a-5bdc-97e0-2f5a05c973a2"
